import { useMemo, useState } from 'react'
import type { Role, Task } from './types'

const modules = import.meta.glob('../data/tasks/*.json', { eager: true, import: 'default' })
const allTasks = Object.values(modules) as Task[]
const ROLES: Role[] = ['팀장', 'Cloud', 'PM', 'FE', 'BE']
const DAY = 86_400_000
const dateValue = (date: string) => Date.parse(`${date}T00:00:00Z`)
const dates = (tasks: Task[]) => { const a=Math.min(...tasks.map(x=>dateValue(x.startDate))), b=Math.max(...tasks.map(x=>dateValue(x.endDate))); return Array.from({length:Math.round((b-a)/DAY)+1},(_,i)=>new Date(a+i*DAY)) }
const week = (date: Date) => { const monday = new Date(date); monday.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7)); return monday.toISOString().slice(5,10).replace('-','/') }

export default function App() {
  const [shown, setShown] = useState(new Set<Role>(ROLES)); const [selected, setSelected] = useState<Task | null>(null)
  const tasks = useMemo(()=>allTasks.filter(x=>shown.has(x.responsible)).sort((a,b)=>dateValue(a.startDate)-dateValue(b.startDate)||a.id.localeCompare(b.id)),[shown])
  const calendar = useMemo(()=>dates(tasks.length?tasks:allTasks),[tasks]); const start=calendar[0]
  const weeks = calendar.reduce<{label:string;span:number}[]>((out,date)=>{const label=week(date);const last=out.at(-1);if(last?.label===label)last.span++;else out.push({label,span:1});return out},[])
  const successor=(task:Task)=>allTasks.filter(x=>x.predecessorIds.includes(task.id)).map(x=>x.title).join(', ')
  return <main className="wbs-page"><header><div><p className="kicker">PROJECT WBS</p><h1>프로젝트 WBS</h1><p>작업 JSON을 기준으로 표시하는 읽기 전용 일정표</p></div><div className="summary"><b>가중 진척률</b><strong>{Math.round(tasks.reduce((sum,t)=>sum+(t.progress ?? (t.status==='completed'?1:0))*(t.weight ?? 0),0)*100)}%</strong></div></header>
  <nav className="role-filter" aria-label="수행인력 필터">{ROLES.map(role=><button className={shown.has(role)?'on':''} key={role} onClick={()=>setShown(old=>{const next=new Set(old);next.has(role)?next.delete(role):next.add(role);return next})}>{role}</button>)}</nav>
  <div className="wbs-scroll"><table><colgroup><col className="division"/><col className="code"/><col className="job"/><col className="type"/><col className="output"/><col className="person"/><col className="date"/><col className="date"/><col className="percent"/><col className="percent"/>{calendar.map((_,i)=><col className="day" key={i}/>)}</colgroup><thead><tr className="week-head"><th colSpan={10}>단계</th>{weeks.map((item,i)=><th key={i} colSpan={item.span}>W{i+1}<small>{item.label}</small></th>)}</tr><tr className="day-head"><th>구분</th><th>WBS</th><th>업무</th><th>유형</th><th>산출물</th><th>수행인력</th><th>시작일</th><th>종료일</th><th>가중치</th><th>진행률</th>{calendar.map(date=><th key={date.toISOString()} className={date.getUTCDay()===0||date.getUTCDay()===6?'weekend':''}><b>{date.getUTCDate()}</b><small>{['일','월','화','수','목','금','토'][date.getUTCDay()]}</small></th>)}</tr></thead><tbody>{tasks.map((task,index)=>{const first=index===0||tasks[index-1].section!==task.section;const offset=Math.round((dateValue(task.startDate)-start.getTime())/DAY), length=Math.round((dateValue(task.endDate)-dateValue(task.startDate))/DAY)+1;return <>{first&&<tr className="section" key={`${task.section}-section`}><td colSpan={10}>{task.section}</td><td colSpan={calendar.length}/></tr>}<tr key={task.id} onClick={()=>setSelected(task)}><td>{first?'착수 및 공통 분석·설계':''}</td><td>{task.wbs ?? task.id}</td><td className="task-name">{task.title}</td><td>{task.category ?? task.phase}</td><td>{task.deliverables.map(x=>x.label).join(', ')}</td><td>{[task.responsible,...task.assistants].join(', ')}</td><td>{task.startDate}</td><td>{task.endDate}</td><td>{Math.round((task.weight ?? 0)*100)}%</td><td>{Math.round((task.progress ?? (task.status==='completed'?1:0))*100)}%</td>{calendar.map((_,i)=><td key={i} className={`slot ${i>=offset&&i<offset+length?'filled':''}`}/>)}</tr></>})}</tbody></table></div>
  {selected&&<div className="modal" onMouseDown={()=>setSelected(null)}><article onMouseDown={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><p className="kicker">{selected.wbs ?? selected.id}</p><h2>{selected.title}</h2><dl><dt>수행인력</dt><dd>{[selected.responsible,...selected.assistants].join(', ')}</dd><dt>기간</dt><dd>{selected.startDate} ~ {selected.endDate}</dd><dt>산출물</dt><dd>{selected.deliverables.map(x=>x.label).join(', ') || '없음'}</dd><dt>후행 작업</dt><dd>{successor(selected)||'없음'}</dd><dt>비고</dt><dd>{selected.notes||'없음'}</dd></dl></article></div>}</main>
}
